!acme.	   

+!test 
	<- /* creating a wsp with a custom 2d topology */
	   createWorkspaceWithTopology("wsp","acme.Space2D");
	   
	   /* joining the workspace with custom agent body artifact */
	   joinWorkspaceWithBody("wsp","acme.MyAgentBodyArtifact",Wid);

	   /* initialising 2d pos + observability radius + observable radius */
	   initBody(0,0,2,2);
	   
	   /* creating situated artifacts */
	   println("creating situated artifacts..");
       makeArtifact("a0","acme.MySituatedArtifact",[50,50,5],Id);
       makeArtifact("a1","acme.MySituatedArtifact",[100,100,5],Id2);
 
 		
       println("should not perceive anyone... (for 1 sec)");
	   inc [artifact_id(Id2)];
       .wait(1000);
       println("now moving to (99,99), near to a1");
	   moveBodyTo(99,99).

+pos(X,Y)[artifact_id(Id)] 
	<- println("I'm able to perceive ",Id," - pos ",X," ",Y).

	   	   
+count(X)[artifact_id(Id)] 
	<- println("detected count: ",X," in ",Id);
	   println("moving the artifact ",Id," away...");
	   moveTo(70,70)[artifact_id(Id)].

-count(X)
	<- println("no more able to observe the count.").
	
/* 
 * TODO: bug fix, the following one including annot does not work, i.e. 
 *        the event is generated by the plan is not selected:
 */
/*
-count(X)[artifact_id(Id)]
	<- println("no more observable: ", Id).

*/
	

	