/* Generated By:JavaCC: Do not edit this line. ArtifactManualParserConstants.java */
package cartago.manual.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ArtifactManualParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 7;
  /** RegularExpression Id. */
  int RBRACE = 8;
  /** RegularExpression Id. */
  int MAN = 9;
  /** RegularExpression Id. */
  int UPROT = 10;
  /** RegularExpression Id. */
  int PRE = 11;
  /** RegularExpression Id. */
  int FUNCT = 12;
  /** RegularExpression Id. */
  int BODY = 13;
  /** RegularExpression Id. */
  int VAR = 14;
  /** RegularExpression Id. */
  int TK_TRUE = 15;
  /** RegularExpression Id. */
  int TK_FALSE = 16;
  /** RegularExpression Id. */
  int TK_NOT = 17;
  /** RegularExpression Id. */
  int TK_NEG = 18;
  /** RegularExpression Id. */
  int TK_INTDIV = 19;
  /** RegularExpression Id. */
  int TK_INTMOD = 20;
  /** RegularExpression Id. */
  int NUMBER = 21;
  /** RegularExpression Id. */
  int EXPONENT = 22;
  /** RegularExpression Id. */
  int STRING = 23;
  /** RegularExpression Id. */
  int ATOM = 24;
  /** RegularExpression Id. */
  int UNNAMEDVAR = 25;
  /** RegularExpression Id. */
  int CHAR = 26;
  /** RegularExpression Id. */
  int LETTER = 27;
  /** RegularExpression Id. */
  int LC_LETTER = 28;
  /** RegularExpression Id. */
  int UP_LETTER = 29;
  /** RegularExpression Id. */
  int DIGIT = 30;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"{\"",
    "\"}\"",
    "\"manual\"",
    "\"usageprot\"",
    "\":precond\"",
    "\":function\"",
    "\":body\"",
    "<VAR>",
    "\"true\"",
    "\"false\"",
    "\"not\"",
    "\"~\"",
    "\"div\"",
    "\"mod\"",
    "<NUMBER>",
    "<EXPONENT>",
    "<STRING>",
    "<ATOM>",
    "<UNNAMEDVAR>",
    "<CHAR>",
    "<LETTER>",
    "<LC_LETTER>",
    "<UP_LETTER>",
    "<DIGIT>",
    "\";\"",
    "\"!\"",
    "\"!!\"",
    "\"?\"",
    "\"+\"",
    "\"-\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"[\"",
    "\"|\"",
    "\"]\"",
    "\"&\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"==\"",
    "\"\\\\==\"",
    "\"=\"",
    "\"=..\"",
    "\"*\"",
    "\"/\"",
    "\"**\"",
  };

}
